name:                deps-sensor
version:             0.1.0
homepage:            https://github.com/matsubara0507/deps-sensor#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          nobutada0507@gmail.com
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/deps-sensor#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- extensible >= 0.6
- fallible
- github >= 0.24
- memory
- mix
- mix-plugin-github
- yaml

library:
  source-dirs: src

executables:
  deps-sensor:
    main: Main.hs
    source-dirs: app
    dependencies:
    - deps-sensor
    - githash
    - dotenv

tests:
  deps-sensor-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - deps-sensor
    - tasty
    - tasty-hspec
    other-modules: []
